// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkoHwgnu2a2M2b8W00A3fSuKMks8euRTY',
    appId: '1:110714445674:web:18464d2b75d9988f8b8f13',
    messagingSenderId: '110714445674',
    projectId: 'speakup-6690f',
    authDomain: 'speakup-6690f.firebaseapp.com',
    storageBucket: 'speakup-6690f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTJrOHpVAVsS4PPWhS3ywhXH-8gvmN72c',
    appId: '1:110714445674:android:9591f2b816bc6fa88b8f13',
    messagingSenderId: '110714445674',
    projectId: 'speakup-6690f',
    storageBucket: 'speakup-6690f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Fwa5Z3GpVfbEw4DOLeU_1zAMDyX_o_g',
    appId: '1:110714445674:ios:2f85a0a75868414f8b8f13',
    messagingSenderId: '110714445674',
    projectId: 'speakup-6690f',
    storageBucket: 'speakup-6690f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Fwa5Z3GpVfbEw4DOLeU_1zAMDyX_o_g',
    appId: '1:110714445674:ios:2f85a0a75868414f8b8f13',
    messagingSenderId: '110714445674',
    projectId: 'speakup-6690f',
    storageBucket: 'speakup-6690f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkoHwgnu2a2M2b8W00A3fSuKMks8euRTY',
    appId: '1:110714445674:web:b91836a72db847f68b8f13',
    messagingSenderId: '110714445674',
    projectId: 'speakup-6690f',
    authDomain: 'speakup-6690f.firebaseapp.com',
    storageBucket: 'speakup-6690f.firebasestorage.app',
  );
}
